/**
 * Relay data contract - the single source of truth for everything the CLI
 * writes into `.relay/`, everything the dashboard reads back, and everything
 * the Bob rules files instruct Bob to produce.
 *
 * Changing shapes here ripples into the CLI (Sprint 2), the dashboard
 * (Sprint 3), and the Bob rules/skills (Sprint 4) - get it right once.
 */

// ---------------------------------------------------------------------------
// Stages
// ---------------------------------------------------------------------------

/**
 * The nine stages of a Relay task, in pipeline order. This array is the
 * source of truth: `StageId` is derived from it so the runtime order and the
 * type can never drift apart.
 *
 * `docs` is the terminal stage - it fires after `pr` once the task's
 * knowledge has been harvested into `.relay/knowledge/`.
 */
export const STAGES = [
  "onboard",
  "brief",
  "plan",
  "implement",
  "debug",
  "test",
  "review",
  "pr",
  "docs",
] as const;

/** Union of all stage identifiers, derived from {@link STAGES}. */
export type StageId = (typeof STAGES)[number];

// ---------------------------------------------------------------------------
// Stage records
// ---------------------------------------------------------------------------

/** Lifecycle state of a single stage within a task. */
export type StageStatus = "pending" | "running" | "done" | "skipped" | "failed";

/**
 * One completed visit of a stage, stored in {@link StageRecord.history}.
 * Every time a stage is revisited, the outgoing version of its artifact is
 * snapshotted here as plain text so no history is ever overwritten.
 */
export interface StageVisit {
  /** 1-based visit number (the visit that produced this snapshot). */
  visitNumber: number;
  /** ISO 8601 timestamp of when this visit began. */
  startedAt: string;
  /** ISO 8601 timestamp of when this visit completed, or null if it was abandoned. */
  completedAt: string | null;
  /** Wall-clock seconds for this visit, or null if abandoned. */
  durationSec: number | null;
  /**
   * Full Markdown content of the artifact file at the point this visit
   * completed (or was snapshotted before being overwritten by the next
   * visit). Stored inline to avoid file sprawl.
   */
  artifactSnapshot: string | null;
  /**
   * Plain-text change summary generated by diffing this snapshot against the
   * artifact content written by the subsequent visit. Null until the next
   * visit's `stage end` runs the diff. Also null when the snapshot itself is
   * null (no artifact at that point).
   */
  changeSummary: string | null;
}

/**
 * Per-stage state, stored under `Task.stages[stageId]`. Written by the CLI
 * (`stage_start` / `stage_end`) and by Bob rules that mark a stage `skipped`
 * when it doesn't apply to a given task.
 */
export interface StageRecord {
  status: StageStatus;
  /**
   * Filename of the artifact this stage produced (e.g. `"01-plan.md"`),
   * relative to the task's directory. Null until the stage completes.
   */
  artifact: string | null;
  /** ISO 8601 timestamp of when the stage began, or null if not started. */
  startedAt: string | null;
  /** ISO 8601 timestamp of when the stage finished, or null if not finished. */
  completedAt: string | null;
  /** Wall-clock duration in seconds, or null until `completedAt` is set. */
  durationSec: number | null;
  /**
   * How many times `stage start` has been called for this stage (0 = never
   * started, 1 = started once, 2+ = revisited). Incremented on every
   * `stage start`. Absent on old task.json files — {@link readTask} fills in
   * the compat default (1 for done/skipped/failed stages, 0 for pending).
   */
  visitCount?: number;
  /**
   * Every completed or abandoned visit prior to the current one. Each entry
   * captures the artifact content at that point so history is never lost.
   * Absent on old task.json files — {@link readTask} fills in `[]`.
   */
  history?: StageVisit[];
  /**
   * ISO timestamp set when an upstream stage is revisited after this stage
   * had already completed, indicating this stage's artifact may be stale.
   * References the revisit that invalidated it. Cleared when this stage
   * itself is revisited (re-run). Absent/null when not stale.
   */
  staleSince?: string | null;
  /**
   * Optional link to the Bob IDE task whose session-summary screenshot
   * (in `bob_sessions/`) corresponds to this stage's work.
   */
  bobTaskId?: string;
  /**
   * Full Markdown body of `artifact`, embedded at compile time. The
   * dashboard is a pure reader of the compiled snapshot with no access to
   * `.relay/` at runtime, so a stage's artifact text has to travel inside
   * `RelayData` itself rather than being fetched separately. Null until the
   * stage completes, or for a stage with no artifact file (`artifact` is
   * also null in that case). Optional (rather than required-nullable like
   * the other stage fields) so existing `StageRecord` object literals
   * elsewhere in the CLI - written before this field existed - keep
   * type-checking without edits; treat a missing key the same as `null`.
   */
  content?: string | null;
  /**
   * Subagents that ran during this stage, derived from paired
   * `subagent_start`/`subagent_end` events in `.relay/metrics/events.jsonl`
   * and embedded at compile time for the same reason {@link content} is:
   * the dashboard reads only the compiled snapshot, never raw events.
   * Omitted (or empty) for a stage that ran no subagents.
   */
  subagents?: SubagentLane[];
  /**
   * Set only when `status === "failed"`: why the stage was marked failed
   * (usually an abandoned/cancelled run with no usable snapshot) and when.
   */
  failure?: { reason: string; at: string } | null;
  /**
   * ISO timestamp of the last time this stage's artifact/task state was
   * restored from a `.history/` snapshot after a cancelled run. Null/absent
   * otherwise. Surfaced in the dashboard as a "restored from earlier
   * version" note.
   */
  restoredAt?: string | null;
  /**
   * mtime of the artifact file on disk at compile time, embedded for the
   * same reason {@link content} is - the dashboard has no filesystem
   * access. Null until the stage has a real artifact file.
   */
  artifactMtime?: string | null;
}

/** One subagent's timing within a single stage, compiled from paired events. */
export interface SubagentLane {
  name: string;
  startedAt: string;
  /** Null if the matching `subagent_end` hasn't landed yet (still running). */
  completedAt: string | null;
  /** Null while the subagent is still running. */
  durationSec: number | null;
}

// ---------------------------------------------------------------------------
// Acceptance criteria
// ---------------------------------------------------------------------------

/**
 * One requirement extracted from the task's source ticket/issue during the
 * `brief` stage, tracked through `test` and `review`.
 *
 * IMPORTANT: `covered` must only ever be `true` when a real test verifies
 * this criterion. Relay's product requirement is an honest amber state -
 * showing "uncovered" on the dashboard is a feature, not a bug. Never mark
 * something covered because it was merely implemented or discussed.
 */
export interface AcceptanceCriterion {
  /** Stable identifier, e.g. `"AC-1"`. */
  id: string;
  /** The requirement, restated in plain language. */
  text: string;
  /** Where in the source ticket this came from, e.g. `"REF-88.pdf p2 §3"`. */
  source: string;
  /** Whether the requirement as written is concrete enough to test. */
  testable: boolean;
  /**
   * When `testable` is false, the proposed measurable rewrite of the
   * criterion. Null when `testable` is true.
   */
  ambiguityNote: string | null;
  /** Whether a test genuinely exists that verifies this criterion. */
  covered: boolean;
  /** Pointer to the covering test, e.g. `"tests/refund.spec.ts:42"`. Null if uncovered. */
  testRef: string | null;
}

// ---------------------------------------------------------------------------
// Task
// ---------------------------------------------------------------------------

/** Where a task's requirements originated. */
export interface TaskSource {
  type: "ticket" | "issue" | "adhoc";
  /** Identifier or reference within that system, e.g. `"REF-88"` or a GitHub issue URL. */
  ref: string;
}

/**
 * Result of `relay pr check-conflicts`. Null until the check has been run at
 * least once. Stored on the task so the dashboard can show a warning on the
 * PR node without re-running git.
 */
export interface ConflictCheck {
  /** ISO 8601 timestamp of when the check ran. */
  checkedAt: string;
  /** True if at least one conflict was detected against `baseBranch`. */
  hasConflicts: boolean;
  /** Repo-relative paths of conflicted files. Empty when `hasConflicts` is false. */
  files: string[];
  /** The branch the check was run against, e.g. `"main"`. */
  baseBranch: string;
}

/** The full shape of a task's `task.json`, the root record for one Relay run. */
export interface Task {
  /** Stable id, e.g. `"T-000"`. */
  id: string;
  /** URL-safe slug used in the task's directory name, e.g. `"refund-window"`. */
  slug: string;
  /** Human-readable title. */
  title: string;
  source: TaskSource;
  /** ISO 8601 timestamp of task creation. Immutable once set. */
  createdAt: string;
  /**
   * ISO 8601 timestamp of the last write to this task's `task.json`. Set by
   * the CLI's atomic task-write helper (`saveTask`) on every write, so no
   * write path can skip it. Task.json files written before this field
   * existed lack it on disk - `readTask` (./fsutil.ts) fills it in with
   * `createdAt` at read time, so every in-memory `Task` always has it.
   */
  updatedAt: string;
  /**
   * Normalized (lowercase kebab-case, deduplicated, sorted) freeform labels.
   * Task.json files written before this field existed lack it on disk -
   * `readTask` fills it in with `[]` at read time.
   */
  tags: string[];
  /**
   * Whether this task is a Relay-assisted run or a manual baseline run
   * (see {@link RunMode}). Added in Sprint 2 so `stage start`/`stage end` can
   * default an event's mode to the task it belongs to.
   */
  mode: RunMode;
  /** The stage the task is currently on (or finished on). */
  currentStage: StageId;
  /** Per-stage state, one entry per {@link StageId}. */
  stages: Record<StageId, StageRecord>;
  acceptanceCriteria: AcceptanceCriterion[];
  /** Ids of {@link KnowledgeEntry} entries harvested from this task's debug work. */
  knowledgeHarvested: string[];
  /** Repo-relative paths touched during implementation. */
  filesTouched: string[];
  /**
   * When this task is a Relay run being compared against a manual baseline,
   * the id of the baseline task it pairs with (and vice versa).
   */
  baselineTaskId?: string;
  /**
   * Result of the last `relay pr check-conflicts` run. Null (or absent) until
   * the check has been run at least once. The PR stage rules instruct Bob to
   * run the check before writing 07-pr.md; the dashboard uses this to show a
   * warning on the PR node.
   */
  conflictCheck?: ConflictCheck | null;
}

// ---------------------------------------------------------------------------
// Events (.relay/metrics/events.jsonl)
// ---------------------------------------------------------------------------

/**
 * Whether an event came from an actual Relay-assisted run or a manual
 * baseline run performed for comparison. Both are logged to the same
 * `events.jsonl` so the dashboard can compute relay-vs-baseline deltas
 * directly from one file.
 */
export type RunMode = "relay" | "baseline";

interface BaseEvent {
  /** ISO 8601 timestamp. */
  ts: string;
  /** Task id this event belongs to. */
  task: string;
  mode: RunMode;
}

export interface StageStartEvent extends BaseEvent {
  event: "stage_start";
  stage: StageId;
}

export interface StageEndEvent extends BaseEvent {
  event: "stage_end";
  stage: StageId;
  durationSec: number;
  artifact: string;
}

export interface KnowledgeHarvestedEvent extends BaseEvent {
  event: "knowledge_harvested";
  /** Id of the {@link KnowledgeEntry} that was written. */
  id: string;
}

export interface SubagentStartEvent extends BaseEvent {
  event: "subagent_start";
  stage: StageId;
  subagentName: string;
}

export interface SubagentEndEvent extends BaseEvent {
  event: "subagent_end";
  stage: StageId;
  subagentName: string;
}

export interface CriteriaExtractedEvent extends BaseEvent {
  event: "criteria_extracted";
  count: number;
  ambiguousCount: number;
}

/** A running stage was cancelled (explicitly via `relay stage cancel`, or detected as abandoned). */
export interface StageCancelEvent extends BaseEvent {
  event: "stage_cancel";
  stage: StageId;
  /** Why: "explicit" (user ran `relay stage cancel`), "abandoned" (another stage start detected it stuck), "timeout" (`relay recover`). */
  reason: "explicit" | "abandoned" | "timeout";
}

/** A stage's artifact/task.json were rolled back to a `.history/` snapshot after a cancel. */
export interface StageRestoreEvent extends BaseEvent {
  event: "stage_restore";
  stage: StageId;
  /** ISO timestamp naming the snapshot directory that was restored from. */
  snapshot: string;
}

/** A cancelled stage had no usable snapshot, so it was marked `failed` instead of restored. */
export interface StageFailedEvent extends BaseEvent {
  event: "stage_failed";
  stage: StageId;
  reason: string;
}

/**
 * A stage was started again after it had already completed at least once.
 * Emitted by `stage start` when `visitCount > 0` at the time of the revisit.
 */
export interface RevisitDetectedEvent extends BaseEvent {
  event: "revisit_detected";
  /** The stage being revisited. */
  fromStage: StageId;
  /** The current stage that was running when the revisit was detected (same as fromStage for now, reserved for future routing). */
  toStage: StageId;
}

/**
 * A revisited stage completed and the change summary was computed.
 * Emitted by `stage end` when `visitCount > 1`.
 */
export interface StageAmendedEvent extends BaseEvent {
  event: "stage_amended";
  stage: StageId;
  visitNumber: number;
  changeSummary: string;
}

/** Discriminated union of every line shape valid in `events.jsonl`. */
export type RelayEvent =
  | StageStartEvent
  | StageEndEvent
  | KnowledgeHarvestedEvent
  | SubagentStartEvent
  | SubagentEndEvent
  | CriteriaExtractedEvent
  | StageCancelEvent
  | StageRestoreEvent
  | StageFailedEvent
  | RevisitDetectedEvent
  | StageAmendedEvent;

// ---------------------------------------------------------------------------
// Knowledge base (.relay/knowledge/)
// ---------------------------------------------------------------------------

/**
 * One harvested gotcha. Gotchas are the flywheel's fuel: written during
 * `debug` on one task, read during `onboard` on every task after it.
 */
export interface KnowledgeEntry {
  /** Stable id, e.g. `"gotcha-014"`. */
  id: string;
  title: string;
  /** Id of the task this was discovered in. */
  discoveredIn: string;
  /** ISO 8601 timestamp of discovery. */
  discoveredAt: string;
  /** Estimated time lost to this issue before it was understood. */
  costMinutes: number;
  /** What was observed before the cause was known. */
  symptom: string;
  /** What actually caused it. */
  rootCause: string;
  /** How it was fixed. */
  fix: string;
  /** One-line warning for future readers, surfaced during onboarding. */
  watchOut: string;
  /** Repo-relative file:line references relevant to this entry. */
  codeRefs: string[];
  /**
   * Free-text note describing when this entry should be re-verified, e.g.
   * "flag if validators.ts changes >30%". Prevents stale gotchas from being
   * trusted forever as the codebase evolves.
   */
  stalenessCheck: string;
}

// ---------------------------------------------------------------------------
// Compiled dashboard snapshot
// ---------------------------------------------------------------------------

/** Schema version for {@link RelayData}; bump on any breaking shape change. */
export const SCHEMA_VERSION = 4;

/**
 * A `Task` as embedded in the compiled snapshot, with one field the CLI
 * derives at compile time rather than storing in `task.json`: Bob edits
 * artifact files directly on disk without going through the CLI, so a
 * task's true "last touched" time has to be computed as the max of
 * `task.json`'s own `updatedAt` and every artifact file's mtime.
 */
export interface CompiledTask extends Task {
  lastEditedAt: string;
}

/** Aggregate duration comparison for one stage, relay run vs. manual baseline. */
export interface StageImpact {
  stage: StageId;
  /** Median seconds spent in this stage across relay runs, or null if no data. */
  relaySec: number | null;
  /** Median seconds spent in this stage across baseline runs, or null if no data. */
  baselineSec: number | null;
}

/** Computed summary the dashboard renders without needing to recompute anything. */
export interface ImpactSummary {
  perStage: StageImpact[];
  /** Total median relay time across all stages, seconds. */
  totalRelaySec: number | null;
  /** Total median baseline time across all stages, seconds. */
  totalBaselineSec: number | null;
  /** Count of acceptance criteria marked `covered: true` across all tasks. */
  criteriaCovered: number;
  /** Total count of acceptance criteria across all tasks. */
  criteriaTotal: number;
  /** Count of cancelled/failed stage runs excluded from every duration above. */
  excludedRuns: number;
}

/**
 * The compiled snapshot written to `dashboard/public/relay-data.json` by the
 * CLI's `compile` command (Sprint 2). The dashboard is a dumb reader of this
 * single file - no server, no live queries.
 */
export interface RelayData {
  schemaVersion: number;
  /** ISO 8601 timestamp of when this snapshot was generated. */
  generatedAt: string;
  tasks: CompiledTask[];
  knowledge: KnowledgeEntry[];
  impact: ImpactSummary;
}
